# Example PatternCatalogSource for testing
apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: PatternCatalogSource
metadata:
  name: default
  namespace: default
spec:
  source: 'https://raw.githubusercontent.com/hybrid-cloud-patterns/patterns-catalog/main/catalog.yaml'
