apiVersion: v1
items:
- apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
  kind: PatternManifest
  metadata:
    labels:
      gitops.hybrid-cloud-patterns.io/source: default
    name: industrial-edge
    namespace: default
  spec:
    organization:
      description: |
        Open source repository of cloud native solution patterns. This repository is maintained by Red Hat with contributions from customers and partners.
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      name: Hybrid Cloud Patterns
      url: https://github.com/hybrid-cloud-patterns
    pattern:
      branch: stable
      description: A horizontal solution for Industrial Edge use cases
      gitRepo: https://github.com/hybrid-cloud-patterns/industrial-edge.git
      longDescription: |
        This pattern demonstrates a horizontal solution for Industrial Edge use cases. It is derived from the MANUela work done by Red Hat Middleware Solution Architects in Germany in 2019/20. The name MANUela stands for MANUfacturing Edge Lightweight Accelerator, you will see this acronym in a lot of artifacts.
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      name: Industrial Edge
      products:
      - Red Hat OpenShift GitOps
      - Red Hat OpenShift Pipelines
      - Red Hat AMQ
      - Red Hat AMQ Streams
      - Red Hat Integration
      - Quay.io
      - Open Data Hub
      - Seldon
      - Hashicorp Vault
      type: Validated
      url: https://hybrid-cloud-patterns.io/patterns/industrial-edge/
- apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
  kind: PatternManifest
  metadata:
    labels:
      gitops.hybrid-cloud-patterns.io/source: default
    name: medical-diagnosis
    namespace: default
  spec:
    organization:
      description: |
        Open source repository of cloud native solution patterns. This repository is maintained by Red Hat with contributions from customers and partners.
      name: Hybrid Cloud Patterns
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      url: https://github.com/hybrid-cloud-patterns
    pattern:
      branch: main
      description: A pattern for doing AI/Ml on images
      gitRepo: https://github.com/hybrid-cloud-patterns/medical-diagnosis.git
      longDescription: |
        This pattern demonstrates a simple architecture for deploying an images recognition and processing application. This Validated Pattern is based  on a demo implementation of an automated data pipeline for chest Xray analysis  previously developed by Red Hat. The original demo can be found here. It  was developed for the US Department of Veteran Affairs.
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      name: Medical Diagnosis
      products:
      - Red Hat Advanced Cluster Management
      - Red Hat OpenShift GitOps
      - OpenShift Serverless
      - OpenDataHub
      - Hashicorp Vault
      type: Validated
      url: https://hybrid-cloud-patterns.io/patterns/medical-diagnosis/
- apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
  kind: PatternManifest
  metadata:
    labels:
      gitops.hybrid-cloud-patterns.io/source: default
    name: multi-cloud-gitops
    namespace: default
  spec:
    organization:
      description: |
        Open source repository of cloud native solution patterns. This repository is maintained by Red Hat with contributions from customers and partners.
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      name: Hybrid Cloud Patterns
      url: https://github.com/hybrid-cloud-patterns
    pattern:
      branch: main
      description: A simple architecture for managing multiple clusters using GitOps
      gitRepo: https://github.com/hybrid-cloud-patterns/multicloud-gitops.git
      longDescription: |
        This pattern demonstrates a simple architecture for managing multiple clusters using GitOps. It can be used as a good starting point for experimenting with other products in a multi-cluster architecture.
      name: Multi-cloud GitOps
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      products:
      - Red Hat Advanced Cluster Management
      - Red Hat OpenShift GitOps
      - Hashicorp Vault
      type: Validated
      url: https://hybrid-cloud-patterns.io/patterns/multicloud-gitops/
- apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
  kind: PatternManifest
  metadata:
    labels:
      gitops.hybrid-cloud-patterns.io/source: default
    name: multicluster-devsecops
    namespace: default
  spec:
    organization:
      description: |
        Open source repository of cloud native solution patterns. This repository is maintained by Red Hat with contributions from customers and partners.
      name: Hybrid Cloud Patterns
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      url: https://github.com/hybrid-cloud-patterns
    pattern:
      branch: main
      description: A horizontal solution for multicluster DevSecOps use cases
      gitRepo: https://github.com/hybrid-cloud-patterns/multicluster-devsecops.git
      longDescription: |
        This pattern demonstrates a horizontal solution for multicluster DevSecOps use cases. It is derived from the multi-cloud GitOps pattern with added products to provide a complete DevSecOps workflow. This includes CI/CD pipelines with security gates; image scanning, signing and storage in a secure registry; deployment to secured clusters that provide advanced security monitoring and alerting.
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      name: Multicluster DevSecOps
      products:
      - Red Hat Advanced Cluster Management
      - Red Hat OpenShift GitOps
      - Red Hat OpenShift Pipelines
      - Red Hat Quay Enterprise
      - Red Hat Open Data Foundation
      - Red Hat Advanced Cluster Security
      - Hashicorp Vault
      type: Community
      url: https://hybrid-cloud-patterns.io/patterns/multicluster-devsecops/
- apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
  kind: PatternManifest
  metadata:
    labels:
      gitops.hybrid-cloud-patterns.io/source: default
    name: retail
    namespace: default
  spec:
    organization:
      description: |
        Open source repository of cloud native solution patterns. This repository is maintained by Red Hat with contributions from customers and partners.
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      name: Hybrid Cloud Patterns
      url: https://github.com/hybrid-cloud-patterns
    pattern:
      branch: main
      description: This pattern demonstrates a pattern that models the store side
        of a retail application.
      gitRepo: https://github.com/hybrid-cloud-patterns/retail.git
      longDescription: |
        This pattern demonstrates a pattern that models the store side of a retail application. It is derived from the Quarkus Coffeeshop Demo done by Red Hat Solution Architects.  The demo models the use of multiple application microservices which use Kafka messaging  to interact and a Postgres database to persist data. (There is a homeoffice analytics  suite in the demo that we hope to include in a later version of the pattern. This demo pulls together several different strands of the demo and allows for multiple stores to be installed on remote clusters via ACM if the user desires. The demo allows users to go to the store’s web page, order drinks and food items,  and see those items “made” and served by the microservices in real time. The pattern includes build pipelines and a demo space, so that changes to the  applications can be tested prior to “production” deployments.
      maintainers:
      - name: Validated Patterns Team
        email: team-validated-patterns@redhat.com
      name: Retail
      products:
      - Red Hat Advanced Cluster Management
      - Red Hat OpenShift GitOps
      - Red Hat OpenShift Pipelines
      - Red Hat AMQ Streams
      - Hashicorp Vault
      type: Community
      url: https://hybrid-cloud-patterns.io/patterns/retail/
kind: List
metadata:
  resourceVersion: ""
