# permissions for end users to view patterns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pattern-viewer-role
rules:
- apiGroups:
  - gitops.hybrid-cloud-patterns.io
  resources:
  - patterns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.hybrid-cloud-patterns.io
  resources:
  - patterns/status
  verbs:
  - get
